version: "3.8"

services:
    django-wsgi:
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Docker/Django_WSGI/Dockerfile
        container_name: django-wsgi
        command: > 
            sh -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py create_super_user &&
                   python manage.py runserver 0.0.0.0:8000"
        ports: 
            - "8000:8000"
        depends_on:
            - open_pycab_database_container
        volumes:
            - ./app:/app
        networks:
            - pycab-app-network

    pycab-nginx:
        build: 
            context: .
            dockerfile: ./Docker/Nginx/Dockerfile
        ports:
          - "8080:80"
        networks:
          - pycab-app-network
        depends_on:
            - django-wsgi
        volumes:
            - .:/app

    open_pycab_database_container:
        image: postgres:16.0
        container_name: open_pycab_database_container
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        ports:
        - "5432:5432"
        networks:
          - pycab-app-network

networks:
  pycab-app-network: