# Generated by Django 4.1 on 2023-11-04 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabCards',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_column='word', max_length=256, null=True)),
                ('text_definition', models.CharField(max_length=4096, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.DecimalField(decimal_places=10, default=0, max_digits=11)),
                ('iterations', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'vocab_cards',
                'db_table': 'vocab_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vocabcards',
            index=models.Index(fields=['id'], name='vocab_id_index'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabcards',
            unique_together={('text', 'text_definition')},
        ),
    ]
