# Generated by Django 4.1 on 2023-11-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_telegram_status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('WAITING_PASSWORD', 'WAITING_PASSWORD'), ('PASSWORD_IS_VALIDATED', 'PASSWORD_IS_VALIDATED')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=4096),
        ),
    ]
